### PR TITLE
86b1u1981

### PR DESCRIPTION
**Pull request by NaRkIsJaHaN**
UI for the mentor-controlled registration form and the email sent to the student after registration.

### CODE REVIEW

**Review by bsaranga — CHANGES_REQUESTED** [review]
Please fix these conflicts.

**Comment by NaRkIsJaHaN** [comment]
resolved

**Review by bsaranga — APPROVED** [review]
Approving, please check this component is well integrated with rest of the app. @NaRkIsJaHaN @thlurte

**Comment by bsaranga** [comment]
@NaRkIsJaHaN please fix merge conflicts.

**Comment by NaRkIsJaHaN** [comment]
resolved

**Review by bsaranga — APPROVED** [review]

**Comment by bsaranga** [comment]
> Approving, please check this component is well integrated with rest of the app. @NaRkIsJaHaN @thlurte 

Merging. Pls do this @NaRkIsJaHaN

**Pull request merged**
